project: 
  type: website
  output-dir: docs
  
website: 
  title: Rushikesh Shivajirao Ware
  navbar:
   left:
      - href: index.qmd
      - text: About
      - blank.qmd
      - blank2.qmd
      
format:
  html: 
     theme: cosco
     css: styless.css
     toc: true